export const data = [
  {
    id: 1,
    first_name: "Abagael",
    last_name: "Girardot",
    email: "agirardot0@cpanel.net",
    gender: "Female",
    postal_code: "20238",
    city: "Washington",
    country: "United States",
    state: "District of Columbia",
    street_address: "88 Hauk Park",
    job_title: "Tax Accountant",
    time_zone: "America/New_York",
    ip_address: "236.234.15.215",
  },
  {
    id: 2,
    first_name: "Mehetabel",
    last_name: "Barnewelle",
    email: "mbarnewelle1@wufoo.com",
    gender: "Female",
    postal_code: "77005",
    city: "Houston",
    country: "United States",
    state: "Texas",
    street_address: "2 Hansons Avenue",
    job_title: "Research Nurse",
    time_zone: "America/Chicago",
    ip_address: "113.78.120.218",
  },
  {
    id: 3,
    first_name: "Stanford",
    last_name: "Yakovich",
    email: "syakovich2@about.me",
    gender: "Male",
    postal_code: "44105",
    city: "Cleveland",
    country: "United States",
    state: "Ohio",
    street_address: "06 Clemons Pass",
    job_title: "VP Quality Control",
    time_zone: "America/New_York",
    ip_address: "119.42.67.253",
  },
  {
    id: 4,
    first_name: "Merle",
    last_name: "Bremmer",
    email: "mbremmer3@blogspot.com",
    gender: "Female",
    postal_code: "10203",
    city: "New York City",
    country: "United States",
    state: "New York",
    street_address: "0 Bluejay Point",
    job_title: "Automation Specialist II",
    time_zone: "America/New_York",
    ip_address: "124.233.82.103",
  },
  {
    id: 5,
    first_name: "Elinor",
    last_name: "Corroyer",
    email: "ecorroyer4@hostgator.com",
    gender: "Female",
    postal_code: "55188",
    city: "Saint Paul",
    country: "United States",
    state: "Minnesota",
    street_address: "16 Starling Hill",
    job_title: "Assistant Professor",
    time_zone: "America/Chicago",
    ip_address: "119.23.176.100",
  },
  {
    id: 6,
    first_name: "Reyna",
    last_name: "Kun",
    email: "rkun5@etsy.com",
    gender: "Female",
    postal_code: "31119",
    city: "Atlanta",
    country: "United States",
    state: "Georgia",
    street_address: "135 Hauk Point",
    job_title: "Administrative Officer",
    time_zone: "America/New_York",
    ip_address: "248.12.127.36",
  },
  {
    id: 7,
    first_name: "Ophelia",
    last_name: "Torrisi",
    email: "otorrisi6@hubpages.com",
    gender: "Female",
    postal_code: "25356",
    city: "Charleston",
    country: "United States",
    state: "West Virginia",
    street_address: "39503 Parkside Parkway",
    job_title: "Quality Control Specialist",
    time_zone: "America/New_York",
    ip_address: "52.195.215.107",
  },
  {
    id: 8,
    first_name: "Winonah",
    last_name: "Butte",
    email: "wbutte7@printfriendly.com",
    gender: "Female",
    postal_code: "77554",
    city: "Galveston",
    country: "United States",
    state: "Texas",
    street_address: "5 Eastwood Lane",
    job_title: "Assistant Media Planner",
    time_zone: "America/Chicago",
    ip_address: "129.195.212.51",
  },
  {
    id: 9,
    first_name: "Harrie",
    last_name: "Wasson",
    email: "hwasson8@princeton.edu",
    gender: "Female",
    postal_code: "28235",
    city: "Charlotte",
    country: "United States",
    state: "North Carolina",
    street_address: "196 Waubesa Way",
    job_title: "GIS Technical Architect",
    time_zone: "America/New_York",
    ip_address: "191.252.13.212",
  },
  {
    id: 10,
    first_name: "Saundra",
    last_name: "Melland",
    email: "smelland9@about.me",
    gender: "Female",
    postal_code: "77218",
    city: "Houston",
    country: "United States",
    state: "Texas",
    street_address: "379 Pierstorff Lane",
    job_title: "Social Worker",
    time_zone: "America/Chicago",
    ip_address: "205.248.160.98",
  },
  {
    id: 11,
    first_name: "Creigh",
    last_name: "Start",
    email: "cstarta@hubpages.com",
    gender: "Male",
    postal_code: "78715",
    city: "Austin",
    country: "United States",
    state: "Texas",
    street_address: "0 Pawling Crossing",
    job_title: "Structural Engineer",
    time_zone: "America/Chicago",
    ip_address: "164.28.224.57",
  },
  {
    id: 12,
    first_name: "Gunilla",
    last_name: "Lorie",
    email: "glorieb@gmpg.org",
    gender: "Female",
    postal_code: "48901",
    city: "Lansing",
    country: "United States",
    state: "Michigan",
    street_address: "16991 Monument Trail",
    job_title: "Budget/Accounting Analyst IV",
    time_zone: "America/Detroit",
    ip_address: "211.6.13.146",
  },
  {
    id: 13,
    first_name: "Konstantine",
    last_name: "Fache",
    email: "kfachec@sciencedaily.com",
    gender: "Male",
    postal_code: "37405",
    city: "Chattanooga",
    country: "United States",
    state: "Tennessee",
    street_address: "919 Shelley Pass",
    job_title: "Internal Auditor",
    time_zone: "America/New_York",
    ip_address: "118.76.231.24",
  },
  {
    id: 14,
    first_name: "Cos",
    last_name: "Middas",
    email: "cmiddasd@slideshare.net",
    gender: "Male",
    postal_code: "77206",
    city: "Houston",
    country: "United States",
    state: "Texas",
    street_address: "62 Claremont Court",
    job_title: "Accounting Assistant II",
    time_zone: "America/Chicago",
    ip_address: "151.129.85.252",
  },
  {
    id: 15,
    first_name: "Elisabet",
    last_name: "Greenmon",
    email: "egreenmone@admin.ch",
    gender: "Female",
    postal_code: "94257",
    city: "Sacramento",
    country: "United States",
    state: "California",
    street_address: "366 Columbus Way",
    job_title: "VP Accounting",
    time_zone: "America/Los_Angeles",
    ip_address: "39.128.6.39",
  },
  {
    id: 16,
    first_name: "Jerrilee",
    last_name: "Yanin",
    email: "jyaninf@smugmug.com",
    gender: "Female",
    postal_code: "28289",
    city: "Charlotte",
    country: "United States",
    state: "North Carolina",
    street_address: "1 West Junction",
    job_title: "Information Systems Manager",
    time_zone: "America/New_York",
    ip_address: "97.145.206.158",
  },
];
